###############################################################
# Discord VC 要約ボット 設定テンプレート
#
# このファイルを `run/config.toml` としてコピーし、
# あなたの環境に合わせて数値やIDを編集してください。
#
# 数値はそのまま、IDは Discord の「開発者モード」で
# 右クリック→「IDをコピー」から取得できます。
###############################################################

# -------------------------------------------------------------
# 対象サーバー（ギルド）ID一覧
# -------------------------------------------------------------
# ボットがスラッシュコマンドを登録するサーバーのIDを配列で指定します。
guild_ids = ["0000000000000000000"]

# -------------------------------------------------------------
# VC 要約機能設定
# -------------------------------------------------------------
[vc_summary]
# ボットが自動参加するために必要な「ミュート解除」ユーザーの最小人数
# 例: 3 にすると、同一VC内のミュート解除ユーザーが3人以上で参加します。
min_users_to_join = 3

# ボットが動作を許可されるボイスチャンネル「カテゴリID」の一覧
# 空配列の場合は全カテゴリを許可します。
allowed_category_ids = ["0000000000000000000"]

# 上記の許可カテゴリ内でも、参加を拒否したい特定の「ボイスチャンネルID」の一覧
denied_channel_ids = []

# 定期要約を投稿する間隔（分）
# 例: 5 で5分ごとに要約を生成・投稿します。0以下で無効化。
summary_interval = 5

# 要約を投稿するテキストチャンネルのID
summary_channel_id = "0000000000000000000"
